BASIC

In [2]:
import numpy as np

In [3]:
my_list = [1, 2, 3, 4, 5]
my_array1 = np.array(my_list)
my_array1


array([1, 2, 3, 4, 5])

In [4]:
my_list2 = [11, 22, 33, 55, 66]

In [5]:
my_lists = [my_list, my_list2]

In [6]:
my_array2 = np.array(my_lists)
my_array2

array([[ 1,  2,  3,  4,  5],
       [11, 22, 33, 55, 66]])

In [7]:
my_array2.shape

(2, 5)

In [7]:
my_array2.dtype

dtype('int64')

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.ones([5, 5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
np.arange(7)

In [13]:
np.arange(7, 100, 8)

ARRAYS AND SCALARS

In [14]:
# for python 2
from __future__ import division

In [15]:
5/2

In [16]:
arr1 = np.array([[1, 2, 3, 4],[8, 9, 10, 11]])
arr1

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [17]:
arr1*arr1

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [18]:
arr1*2

array([[ 2,  4,  6,  8],
       [16, 18, 20, 22]])

INDEXING ARRAYS

In [19]:
arr = np.arange(0, 11)

In [20]:
arr

In [21]:
arr[2]

2

In [22]:
arr[0]

0

In [23]:
arr[1:5]

array([1, 2, 3, 4])

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
arr[0:5] = 100

In [26]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [27]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [29]:
arr_2d = np.array(([5,10,15],[20,25,30],[40,50,60]))   

In [30]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [40, 50, 60]])

In [31]:
arr_2d[1]

array([20, 25, 30])

In [32]:
print(f"arr_2d[1][0]: {arr_2d[1][0]}")
print(f"arr_2d[2][2]: {arr_2d[2][2]}")
print(f"arr_2d[0][3]: {arr_2d[0][2]}")

arr_2d[1][0]: 20
arr_2d[2][2]: 60
arr_2d[0][3]: 15


In [33]:
arr2d = np.zeros((10,10))

In [34]:
arr2d

In [35]:
arr_length = arr2d.shape[1]
arr_length

10

In [36]:
for i in range(arr_length):
    arr2d[i]=1
arr2d

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])