In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [4]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [6]:
A = np.random.randn(10)
A

array([ 0.72717334,  0.24288104,  0.2062917 , -0.12530115, -0.8333649 ,
        0.37886511,  0.93785723, -0.54849377, -0.03793273, -0.77759187])

In [7]:
B = np.random.randn(10)
B

array([-1.34769572, -1.28085721, -4.87503466,  1.62114352,  0.23668028,
        0.68464949,  0.09307142, -1.79295833,  0.21133017,  0.06290596])

In [8]:
np.add(A,B)

array([-0.62052238, -1.03797618, -4.66874296,  1.49584237, -0.59668462,
        1.0635146 ,  1.03092865, -2.3414521 ,  0.17339744, -0.71468592])

In [9]:
np.maximum(A,B)

array([ 0.72717334,  0.24288104,  0.2062917 ,  1.62114352,  0.23668028,
        0.68464949,  0.93785723, -0.54849377,  0.21133017,  0.06290596])